version: '2'
services:
  jenkins-data:
    image: jenkins
    entrypoint:
    - /bin/true
    volumes:
    - /var/jenkins_home
    labels:
      io.rancher.container.start_once: 'true'
  jenkins:
    image: jenkins
    volumes_from:
    - jenkins-data
    labels:
      backup_folder: /var/jenkins_home
      io.rancher.sidekicks: jenkins-data
      io.rancher.container.pull_image: always
